/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.2-4-g944ee75106-20220919"
#endif /* AVUTIL_FFVERSION_H */
